# Site settings
title: விஜய் ரெங்கராஜன்
email: urapvr@gmail.com
description: "என் தமிழ் கட்டுரைகள்"
baseurl: ""
url: "http://urapvr.github.io/tamil"

# Build settings
markdown: redcarpet
permalink: pretty
